name: Test

on:
  push:
  pull_request:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 22

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Compile and Test with Different JVM Flags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flag:
          - "-XX:+UseStringDeduplication"  
          - "-XX:+AlwaysPreTouch"
          - "-XX:+TieredCompilation"
          - "-XX:+PrintGCDetails"
          - "-XX:MaxInlineLevel=15"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Set JVM Flag and Build & Test
        env:
          MAVEN_OPTS: ${{ matrix.flag }}
        run: |
          echo "Running tests with JVM flag: $MAVEN_OPTS"
          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage

      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Fail if coverage has not improved
        run: |
          coverage=$COVERAGE
          threshold=13.43
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved."
            exit 1
          else
            echo "New coverage: $coverage%"
          fi

      - name: Upload test results and coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "test-results-${{ matrix.flag }}"
          path: target/surefire-reports

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "coverage-report-${{ matrix.flag }}"
          path: target/site/jacoco